<!-- All Javascripts -->
<script src="{{ asset('dist-front/js/jquery-3.6.3.min.js') }}"></script>
<script src="{{ asset('dist-front/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('dist-front/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('dist-front/js/wow.min.js') }}"></script>
<script src="{{ asset('dist-front/js/select2.min.js') }}"></script>
<script src="{{ asset('dist-front/js/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('dist-front/js/moment.min.js') }}"></script>
<script src="{{ asset('dist-front/js/dataTables.bootstrap5.min.js') }}"></script>
<script src="{{ asset('dist-front/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('dist-front/js/jquery.meanmenu.js') }}"></script>
<script src="{{ asset('dist-front/tinymce/tinymce.min.js') }}"></script>
<script src="{{ asset('dist-front/js/iziToast.min.js') }}"></script>